server:
  port: 8585

  
  #database connctivity
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogApp  
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
    




logging:
  level:
    '[org.springframework]': debug  
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      